openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /excerpt_with_alignment:
    get:
      summary: Get Excerpt With Alignment
      operationId: get_excerpt_with_alignment
      parameters:
      - name: translation
        in: query
        required: true
        schema:
          type: integer
          title: Translation
      - name: excerpt
        in: query
        required: true
        schema:
          type: string
          title: Excerpt
      - name: voice
        in: query
        required: false
        schema:
          title: Voice
          type: integer
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExcerptWithAlignmentModel'
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleErrorResponse'
          description: Unprocessable Entity
  /check_translation:
    get:
      summary: Check Translation
      operationId: check_translation
      parameters:
      - name: translation
        in: query
        required: true
        schema:
          title: Translation
          type: integer
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /check_voice:
    get:
      summary: Check Translation
      operationId: check_voice
      parameters:
      - name: voice
        in: query
        required: true
        schema:
          title: Voice
          type: integer
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /languages:
    get:
      summary: Get Languages
      operationId: get_languages
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/LanguageModel'
                type: array
                title: Response Get Languages
  /translations:
    get:
      summary: Get Translations
      operationId: get_translations
      parameters:
      - name: language
        in: query
        required: false
        schema:
          title: Language
          type: string
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TranslationModel'
                title: Response Get Translations
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /translation_info:
    get:
      summary: Get Translation Info
      operationId: get_translation_info
      parameters:
      - name: translation
        in: query
        required: true
        schema:
          type: integer
          title: Translation
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TranslationInfoModel'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    BookInfoModel:
      properties:
        code:
          type: integer
          title: Code
        number:
          type: integer
          title: Number
        alias:
          type: string
          title: Alias
        name:
          type: string
          title: Name
        chapters_count:
          type: integer
          title: Chapters Count
      type: object
      required:
      - code
      - number
      - alias
      - name
      - chapters_count
      title: BookInfoModel
    ExcerptWithAlignmentModel:
      properties:
        title:
          type: string
          title: Title
        is_single_chapter:
          type: boolean
          title: Is Single Chapter
        parts:
          items:
            $ref: '#/components/schemas/PartsWithAlignmentModel'
          type: array
          title: Parts
      type: object
      required:
      - title
      - is_single_chapter
      - parts
      title: ExcerptWithAlignmentModel
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    LanguageModel:
      properties:
        alias:
          type: string
          title: Alias
        name_en:
          type: string
          title: Name En
        name_national:
          type: string
          title: Name National
      type: object
      required:
      - alias
      - name_en
      - name_national
      title: LanguageModel
    NoteModel:
      properties:
        code:
          type: integer
          title: Code
        number:
          type: integer
          title: Number
        text:
          type: string
          title: Text
        verse_code:
          type: integer
          title: Verse Code
        position_text:
          type: integer
          title: Position Text
        position_html:
          type: integer
          title: Position Html
      type: object
      required:
      - code
      - number
      - text
      - verse_code
      - position_text
      - position_html
      title: NoteModel
    PartsWithAlignmentModel:
      properties:
        book_number:
          type: integer
          title: Book Number
        book_name:
          type: string
          title: Book Name
        chapter_number:
          type: integer
          title: Chapter Number
        audio_link:
          type: string
          title: Audio Link
        verses:
          items:
            $ref: '#/components/schemas/VerseWithAlignmentModel'
          type: array
          title: Verses
        notes:
          items:
            $ref: '#/components/schemas/NoteModel'
          type: array
          title: Notes
        titles:
          items:
            $ref: '#/components/schemas/TitleModel'
          type: array
          title: Titles
      type: object
      required:
      - book_number
      - book_name
      - chapter_number
      - audio_link
      - verses
      - notes
      - titles
      title: PartsWithAlignmentModel
    SimpleErrorResponse:
      properties:
        detail:
          type: string
          title: Detail
      type: object
      required:
      - detail
      title: SimpleErrorResponse
    TitleModel:
      properties:
        code:
          type: integer
          title: Code
        text:
          type: string
          title: Text
        before_verse_code:
          type: integer
          title: Before Verse Code
      type: object
      required:
      - code
      - text
      - before_verse_code
      title: TitleModel
    TranslationInfoModel:
      properties:
        code:
          type: integer
          title: Code
        alias:
          type: string
          title: Alias
        name:
          type: string
          title: Name
        description:
          title: Description
          type: string
        language:
          type: string
          title: Language
        books_info:
          items:
            $ref: '#/components/schemas/BookInfoModel'
          type: array
          title: Books Info
      type: object
      required:
      - code
      - alias
      - name
      - language
      - books_info
      title: TranslationInfoModel
    TranslationModel:
      properties:
        code:
          type: integer
          title: Code
        alias:
          type: string
          title: Alias
        name:
          type: string
          title: Name
        description:
          title: Description
          type: string
        language:
          type: string
          title: Language
        voices:
          items:
            $ref: '#/components/schemas/VoiceModel'
          type: array
          title: Voices
      type: object
      required:
      - code
      - alias
      - name
      - language
      - voices
      title: TranslationModel
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    VerseWithAlignmentModel:
      properties:
        code:
          type: integer
          title: Code
        number:
          type: integer
          title: Number
        join:
          type: integer
          title: Join
        text:
          type: string
          title: Text
        html:
          type: string
          title: Html
        begin:
          type: number
          title: Begin
        end:
          type: number
          title: End
        start_paragraph:
          type: boolean
          title: Start Paragraph
      type: object
      required:
      - code
      - number
      - join
      - text
      - html
      - begin
      - end
      - start_paragraph
      title: VerseWithAlignmentModel
    VoiceModel:
      properties:
        code:
          type: integer
          title: Code
        alias:
          type: string
          title: Alias
        name:
          type: string
          title: Name
        description:
          title: Description
          type: string
        is_music:
          type: boolean
          title: Is Music
      type: object
      required:
      - code
      - alias
      - name
      - is_music
      title: VoiceModel
