openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /excerpt_with_alignment:
    get:
      summary: Get Excerpt With Alignment
      operationId: get_excerpt_with_alignment
      parameters:
      - name: translation
        in: query
        required: true
        schema:
          type: integer
          title: Translation
      - name: excerpt
        in: query
        required: true
        schema:
          type: string
          title: Excerpt
      - name: voice
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: Voice
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExcerptWithAlignmentModel'
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleErrorResponse'
          description: Unprocessable Entity
  /languages:
    get:
      summary: Get Languages
      operationId: get_languages
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/LanguageModel'
                type: array
                title: Response Get Languages
  /translations:
    get:
      summary: Get Translations
      operationId: get_translations
      parameters:
      - name: language
        in: query
        required: false
        schema:
          title: Language
          type: string
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TranslationModel'
                title: Response Get Translations
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    ExcerptWithAlignmentModel:
      properties:
        title:
          type: string
          title: Title
        parts:
          items:
            $ref: '#/components/schemas/PartsWithAlignmentModel'
          type: array
          title: Parts
      type: object
      required:
      - title
      - parts
      title: ExcerptWithAlignmentModel
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    LanguageModel:
      properties:
        alias:
          type: string
          title: Alias
        name_en:
          type: string
          title: Name En
        name_national:
          type: string
          title: Name National
      type: object
      required:
      - alias
      - name_en
      - name_national
      title: LanguageModel
    PartsWithAlignmentModel:
      properties:
        book_number:
          type: integer
          title: Book Number
        chapter_number:
          type: integer
          title: Chapter Number
        verses:
          items:
            $ref: '#/components/schemas/VerseWithAlignmentModel'
          type: array
          title: Verses
      type: object
      required:
      - book_number
      - chapter_number
      - verses
      title: PartsWithAlignmentModel
    SimpleErrorResponse:
      properties:
        detail:
          type: string
          title: Detail
      type: object
      required:
      - detail
      title: SimpleErrorResponse
    TranslationModel:
      properties:
        code:
          type: integer
          title: Code
        alias:
          type: string
          title: Alias
        name:
          type: string
          title: Name
        description:
          title: Description
          type: string
        language:
          type: string
          title: Language
        voices:
          items:
            $ref: '#/components/schemas/VoiceModel'
          type: array
          title: Voices
      type: object
      required:
      - code
      - alias
      - name
      - language
      - voices
      title: TranslationModel
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    VerseWithAlignmentModel:
      properties:
        code:
          type: integer
          title: Code
        number:
          type: integer
          title: Number
        text:
          type: string
          title: Text
        begin:
          type: number
          title: Begin
        end:
          type: number
          title: End
        start_paragraph:
          type: boolean
          title: Start Paragraph
      type: object
      required:
      - code
      - number
      - text
      - begin
      - end
      - start_paragraph
      title: VerseWithAlignmentModel
    VoiceModel:
      properties:
        code:
          type: integer
          title: Code
        alias:
          type: string
          title: Alias
        name:
          type: string
          title: Name
        description:
          title: Description
          type: string
        is_music:
          type: boolean
          title: Is Music
      type: object
      required:
      - code
      - alias
      - name
      - is_music
      title: VoiceModel
